Repository CruGlobal/kotlin-mpp-godtools-tool-parser, pull requests merged in 2025-05, with the labels that each got.

#799 GT-2598 Switch parser model to return colormath Color instead of PlatformColor
  gradle.properties
  module/common/build.gradle.kts
  module/interop/build.gradle.kts
  module/interop/src/iosMain/kotlin/org/cru/godtools/shared/interop/colormath/Color.kt
  module/parser/build.gradle.kts
  module/parser/src/androidMain/kotlin/org/cru/godtools/shared/tool/parser/model/PlatformColor.android.kt
  module/parser/src/androidMain/kotlin/org/cru/godtools/shared/tool/parser/model/Text.android.kt
  module/parser/src/androidMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/Page.android.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/internal/Color.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Button.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Card.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Constants.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Manifest.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Multiselect.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/PlatformColor.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Styles.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/StylesOverride.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Text.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/lesson/Constants.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/lesson/LessonPage.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/CardCollectionPage.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/Constants.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/Page.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/CallToAction.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/Header.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/Modal.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPage.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/internal/ColorTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ColorTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ManifestTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/MultiselectTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/StylesTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/TestColors.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/lesson/LessonPageTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/page/PageTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/util/ColorTestUtils.kt
  module/parser/src/iosMain/kotlin/org/cru/godtools/shared/tool/parser/model/PlatformColor.ios.kt
  module/parser/src/jsMain/kotlin/org/cru/godtools/shared/tool/parser/model/PlatformColor.js.kt
Labels: Publish PR SNAPSHOT: CocoaPods, ios-framework-headers-changed, typescript-headers-changed

#809 GT-2606 Move EventId to make it visible to the State object
  build.gradle.kts
  module/parser-base/build.gradle.kts
  module/parser-base/src/androidMain/kotlin/org/cru/godtools/shared/tool/state/internal/Parcelable.kt
  module/parser-base/src/androidUnitTest/kotlin/org/cru/godtools/shared/tool/state/StateParcelizeTest.kt
  module/parser-base/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/EventId.kt
  module/parser-base/src/commonMain/kotlin/org/cru/godtools/shared/tool/state/State.kt
  module/parser-base/src/commonMain/kotlin/org/cru/godtools/shared/tool/state/internal/Parcelable.kt
  module/parser-base/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/EventIdTest.kt
  module/parser-base/src/commonTest/kotlin/org/cru/godtools/shared/tool/state/StateTest.kt
  module/parser-base/src/iosMain/kotlin/org/cru/godtools/shared/tool/state/internal/Parcelable.kt
  module/parser-base/src/jsMain/kotlin/org/cru/godtools/shared/tool/state/internal/Parcelable.kt
  module/parser-expressions/build.gradle.kts
  module/parser/build.gradle.kts
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Animation.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Clickable.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/EventId+Parsing.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/EventId.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Manifest.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/Page.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/Modal.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPage.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/AnimationTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ButtonTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/EventIdParsingTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ManifestTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/MultiselectTest.kt
  publishing/npm/build.gradle.kts
  settings.gradle.kts
Labels: ios-framework-headers-changed, typescript-headers-changed

#795 GT-2594 GT-2623 Setup a new compose renderer module
  .editorconfig
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/git-lfs-validation.yml
  .github/workflows/record-snapshots.yml
  build.gradle.kts
  gradle/libs.versions.toml
  module/parser/build.gradle.kts
  module/renderer/build.gradle.kts
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/BasePaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderTextPaparazziTest.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/Constants.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderContent.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderContentStack.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderText.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/extensions/Text+Compose.kt
  module/renderer/src/iosMain/kotlin/org/cru/godtools/shared/renderer/content/ContentStackView.kt
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Color.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Font_Weight.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Simple.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Styles.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Text_Align.png
  settings.gradle.kts
Labels: Publish PR SNAPSHOT: CocoaPods, Publish PR SNAPSHOT: Maven, ios-framework-headers-changed

#810 GT-2628 update Manifest.locale to be a fluidsonic locale
  module/parser/build.gradle.kts
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/internal/fluidlocale/String.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Manifest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ManifestTest.kt
Labels: Publish PR SNAPSHOT: npm, Publish PR SNAPSHOT: CocoaPods, Publish PR SNAPSHOT: Maven, ios-framework-headers-changed, typescript-headers-changed

#822 GT-2639 Refactor AnalyticsEvent to make it usable from renderer state
  module/parser-base/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent.kt
  module/parser-base/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEventTest.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Accordion.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent+Parsing.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Button.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Link.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Multiselect.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Tabs.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/lesson/LessonPage.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/CardCollectionPage.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/ContentPage.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/PageCollectionPage.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/Hero.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPage.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEventParsingTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/MultiselectTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/lesson/LessonPageTest.kt
  module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/page/CardCollectionPageTest.kt
  module/renderer-state/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent+State.kt
  module/renderer-state/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEventStateTest.kt
Labels: Publish PR SNAPSHOT: npm, Publish PR SNAPSHOT: CocoaPods, ios-framework-headers-changed, typescript-headers-changed

#812 GT-2606 Support button elements in the new renderer
  build-logic/src/main/kotlin/AndroidConfig.kt
  gradle/libs.versions.toml
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Button.kt
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Dimension.kt
  module/renderer-state/build.gradle.kts
  module/renderer-state/src/commonMain/kotlin/org/cru/godtools/shared/renderer/state/State.kt
  module/renderer-state/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent+State.kt
  module/renderer-state/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/EventId+State.kt
  module/renderer-state/src/commonTest/kotlin/org/cru/godtools/shared/renderer/state/StateTest.kt
  module/renderer/build.gradle.kts
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderButtonPaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderContentStackPaparazziTest.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderButton.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderContent.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderContentStack.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderParagraph.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/extensions/Clickable+State.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/extensions/Gravity+Compose.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/extensions/HasAnalyticsEvents+State.kt
  module/renderer/src/commonTest/kotlin/org/cru/godtools/shared/renderer/TestConstants.kt
  module/renderer/src/commonTest/kotlin/org/cru/godtools/shared/renderer/content/BaseRenderContentTest.kt
  module/renderer/src/commonTest/kotlin/org/cru/godtools/shared/renderer/content/RenderButtonTest.kt
  module/renderer/src/commonTest/kotlin/org/cru/godtools/shared/renderer/content/extensions/ClickableStateTest.kt
  module/renderer/src/commonTest/kotlin/org/cru/godtools/shared/renderer/content/extensions/HasAnalyticsEventsStateTest.kt
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderButtonPaparazziTest_RenderButton()_-_Color.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderButtonPaparazziTest_RenderButton()_-_Defaults.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderButtonPaparazziTest_RenderButton()_-_Gravity.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderButtonPaparazziTest_RenderButton()_-_Width.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderContentStackPaparazziTest_RenderContentStack()_-_LTR.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderContentStackPaparazziTest_RenderContentStack()_-_RTL.png
Labels: ios-framework-headers-changed, typescript-headers-changed

#823 GT-2637 add support for link element
  module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Link.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/BasePaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderButtonPaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderContentStackPaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderLinkAccessibilityPaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderLinkPaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderParagraphPaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderSpacerPaparazziTest.kt
  module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderTextPaparazziTest.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderContent.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderContentStack.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderLink.kt
  module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/extensions/Text+Compose.kt
  module/renderer/src/commonTest/kotlin/org/cru/godtools/shared/renderer/content/RenderLinkTest.kt
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderButtonPaparazziTest_RenderButton()_-_Color.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderButtonPaparazziTest_RenderButton()_-_Defaults.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderButtonPaparazziTest_RenderButton()_-_Gravity.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderButtonPaparazziTest_RenderButton()_-_Width.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderContentStackPaparazziTest_RenderContentStack()_-_LTR.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderContentStackPaparazziTest_RenderContentStack()_-_RTL.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderLinkAccessibilityPaparazziTest_RenderLink()_-_TextAlign.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderLinkPaparazziTest_RenderLink()_-_Simple.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderLinkPaparazziTest_RenderLink()_-_TextAlign.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderParagraphPaparazziTest_RenderParagraph()_-_Defaults.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderSpacerPaparazziTest_RenderSpacer()_-_Fixed_Spacer_In_Middle.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderSpacerPaparazziTest_RenderSpacer()_-_Fixed_Spacer_On_Bottom.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderSpacerPaparazziTest_RenderSpacer()_-_Fixed_Spacer_On_Top.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderSpacerPaparazziTest_RenderSpacer()_-_Multiple_Fixed_Spacers.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Color.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Font_Weight.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Simple.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Styles.png
  module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Text_Align.png
Labels: ios-framework-headers-changed, typescript-headers-changed
